services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    restart: unless-stopped
    container_name: palworld-server
    stop_grace_period: 30s
    ports:
      - 8211:8211/udp
      - 27015:27015/udp
      # - 8212:8212/tcp  # Port for REST API if REST_API_ENABLED: true
    environment:
      PUID: 1000
      PGID: 1000
      PORT: 8211
      PLAYERS: 10
      SERVER_PASSWORD: "mltsf"
      MULTITHREADING: true
      RCON_ENABLED: true
      RCON_PORT: 25575
      TZ: "Europe/Berlin"
      ADMIN_PASSWORD: "adminPasswordHere"
      COMMUNITY: true
      SERVER_NAME: "MLTSF"
      SERVER_DESCRIPTION: "Palworld server of MLTSF"
      ALLOW_CONNECT_PLATFORM: "Steam"
      EXP_RATE: 2.5
      PAL_CAPTURE_RATE: 1.3
      PLAYER_STAMINA_DECREASE_RATE: 0.5
      ITEM_WEIGHT_RATE: 0.5
      DEATH_PENALTY: "Item"
      BASE_CAMP_MAX_NUM_IN_GUILD: 6
      CAN_PICKUP_OTHER_GUILD_DEATH_PENALTY_DROP: true
      BASE_CAMP_WORKER_MAX_NUM: 50
    volumes:
      - ./palworld:/palworld/