services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    restart: unless-stopped
    container_name: palworld-server
    stop_grace_period: 30s
    ports:
      - 8211:8211/udp
      - 27015:27015/udp
    environment:
      ADMIN_PASSWORD: ${PALWORLD_SERVER_ADMIN_PASSWORD}
      ALLOW_CONNECT_PLATFORM: "Steam"
      COMMUNITY: true
      MULTITHREADING: true
      PGID: 1000
      PLAYERS: 10
      PORT: 8211
      PUID: 1000
      RCON_ENABLED: true
      RCON_PORT: 25575
      SERVER_DESCRIPTION: "Palworld server of MLTSF"
      SERVER_NAME: "MLTSF"
      SERVER_PASSWORD: ${PALWORD_SERVER_PASSWORD}
      TZ: "Europe/Berlin"
      BASE_CAMP_MAX_NUM_IN_GUILD: 6
      BASE_CAMP_WORKER_MAX_NUM: 50
      BUILD_OBJECT_DAMAGE_RATE: 0
      BUILD_OBJECT_DETERIORATION_DAMAGE_RATE: 0
      CAN_PICKUP_OTHER_GUILD_DEATH_PENALTY_DROP: true
      DEATH_PENALTY: "None"
      EXP_RATE: 2.5
      ITEM_WEIGHT_RATE: 0.5
      PAL_CAPTURE_RATE: 1.3
      PAL_EGG_DEFAULT_HATCHING_TIME: 2
      PLAYER_STAMINA_DECREASE_RATE: 0.5
    volumes:
      - /home/fkoch/palworld:/palworld/